apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: s3:{{ .bucket_endpoint | toString }}
        AWS_ACCESS_KEY_ID: {{ .cf_access_key_id | toString }}
        AWS_SECRET_ACCESS_KEY: {{ .cf_access_key_secret | toString }}

  data:
  - secretKey: bucket_endpoint
    remoteRef:
      key: volsync-r2
      property: bucket_endpoint
  - secretKey: cf_access_key_id
    remoteRef:
      key: volsync-r2
      property: cf_access_key_id
  - secretKey: cf_access_key_secret
    remoteRef:
      key: volsync-r2
      property: cf_access_key_secret
