apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  chart:
    spec:
      chart: volsync
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
      version: 0.12.1
  interval: 15m
