apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: grafana
  commonMetadata:
    labels:
      service: grafana
  interval: 5m
  path: ./apps/base/grafana/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
