---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: crunchydata-pgo
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry.developers.crunchydata.com/crunchydata/pgo
  ref:
    tag: 5.8.2
