---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    semver: v5.18.0