apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 27.17.0
  interval: 15m
  values:
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-pushgateway:
      enabled: false
