apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: prometheus
   namespace: prometheus
spec:
  sourcePVC: prometheus-server
  trigger:
    # Run backup daily @ midnight
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 7
    # Name of secret with bucket config
    repository: volsync-r2
    # Backup retention policy
    retain:
      daily: 7
    # Use Snapshot method for longhorn
    copyMethod: Snapshot
