apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  targetNamespace: secret-ops
  commonMetadata:
    labels:
      service: external-secrets
  # dependsOn:
  #   - name: onepassword-connect
  interval: 5m
  path: ./apps/base/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
