apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
spec:
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      version: 1.15.1
  interval: 15m
# defaults to secret>op-credentials>1password-credentials.json
