apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
spec:
  chart:
    spec:
      chart: onepassword-connect
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: flux-system
      version: 1.15.1
  interval: 15m
