apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  targetNamespace: it-tools
  commonMetadata:
    labels:
      service: it-tools
  interval: 5m
  path: ./apps/base/it-tools/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
