apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  chart:
    spec:
      chart: gatus
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
      version: 1.2.0
  interval: 15m