apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  chartRef:
    kind: OCIRepository
    name: grafana-operator
    namespace: flux-system
  interval: 15m