apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: kube-ops-view
spec:
  chart:
    spec:
      chart: kube-ops-view
      sourceRef:
        kind: HelmRepository
        name: j6nca
        namespace: flux-system
      version: 1.0.0
  interval: 15m
