apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  targetNamespace: reloader
  commonMetadata:
    labels:
      service: reloader
  interval: 5m
  path: ./apps/base/reloader/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
