apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 75.3.3
  interval: 15m
  values:
    crds:
      enabled: true
    # Managed in standalone chart
    grafana:
      enabled: true
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    windowsMonitoring:
      enabled: false
    
    prometheusOperator:
      prometheusSpec:
        retention: "15d"
