apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 75.3.3
  interval: 15m
  values:
    # Shorten resource names
    fullnameOverride: kps
    crds:
      enabled: true
    alertmanager:
      enabled: true
      serviceMonitor:
        enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 1Gi

    grafana:
      enabled: false
      defaultDashboardsTimezone: 'America/Toronto'
      # Deploy grafana dashboards associated with this chart
      forceDeployDashboards: true
      defaultDashboardsEnabled: true
      sidecar:
        dashboards:
          enabled: false
          # Store default dashboards in 'Kubernetes' folder. A lot of these are defaults already but this gives better visibility
          # of their settings in such a complex chart.
          # Ref: https://github.com/grafana/helm-charts/issues/527#issuecomment-982319638
          annotations:
            grafana_folder: Kubernetes

    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    windowsMonitoring:
      enabled: false
    
    prometheus:
      prometheusSpec:
        image:
          registry: docker.io
          repository: prompp/prompp
          tag: 2.53.2-0.2.6
        securityContext:
          fsGroup: 64535
          runAsGroup: 64535
          runAsNonRoot: true
          runAsUser: 64535
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        retention: 15d
        retentionSize: 15GB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 15Gi
