apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  chart:
    spec:
      chart: alertmanager
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 1.13.1
  interval: 15m
