apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  targetNamespace: alertmanager
  commonMetadata:
    labels:
      service: alertmanager
  interval: 5m
  path: ./apps/base/alertmanager/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
