apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  commonMetadata:
    labels:
      service: longhorn
  interval: 5m
  path: ./apps/base/longhorn/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
