apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  targetNamespace: cloudflare-tunnel
  commonMetadata:
    labels:
      service: cloudflare-tunnel
  dependsOn:
    - name: external-secrets-resources
  interval: 5m
  path: ./apps/base/cloudflare-tunnel/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
