apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  targetNamespace: kube-state-metrics
  commonMetadata:
    labels:
      service: kube-state-metrics
  interval: 5m
  path: ./apps/base/kube-state-metrics/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
