apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  chartRef:
    kind: OCIRepository
    name: crunchydata-pgo
    namespace: flux-system
  interval: 15m
