apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/base/onepassword-connect/kustomize.yaml
  - ./namespace.yaml
commonMetadata:
  labels:
    cluster: homelab
