apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatus
  namespace: flux-system
spec:
  targetNamespace: gatus
  commonMetadata:
    labels:
      service: gatus
  dependsOn:
    - name: kube-prometheus-stack
  interval: 5m
  path: ./apps/base/gatus/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
