apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  targetNamespace: onepassword-connect
  commonMetadata:
    labels:
      service: onepassword-connect
  # dependsOn:
  #   - name: onepassword-connect
  interval: 5m
  path: ./apps/base/onepassword-connect/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
