apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  targetNamespace: postgres-operator
  commonMetadata:
    labels:
      service: postgres-operator
  interval: 5m
  path: ./apps/base/postgres-operator/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
