apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://_connect-api._tcp.onepassword-connect.onepassword-connect
      vaults:
        lab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-token
            key: token
            namespace: onepassword-connect
                                                                                        