apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword-connect.svc.cluster.local:8080
      vaults:
        lab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-token
            key: token
            namespace: secret-ops
                                                                                        