apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yopass
  namespace: flux-system
spec:
  targetNamespace: yopass
  commonMetadata:
    labels:
      service: yopass
  interval: 5m
  path: ./apps/base/yopass/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
