apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  targetNamespace: volsync
  commonMetadata:
    labels:
      service: volsync
  interval: 5m
  path: ./apps/base/volsync/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
