apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-cats
  namespace: kube-cats
spec:
  chart:
    spec:
      chart: kube-cats
      sourceRef:
        kind: HelmRepository
        name: j6nca
        namespace: flux-system
      version: 1.0.5
  interval: 15m
