apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  targetNamespace: prometheus
  commonMetadata:
    labels:
      service: prometheus
  interval: 5m
  path: ./apps/base/prometheus/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
