apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  targetNamespace: prometheus
  dependsOn:
    - name: longhorn
  commonMetadata:
    labels:
      service: prometheus
  interval: 5m
  path: ./apps/base/prometheus/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-replication
  namespace: flux-system
spec:
  targetNamespace: prometheus
  dependsOn:
    - name: volsync
    - name: prometheus
  interval: 5m
  path: ./apps/base/prometheus/replication
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
